#[cfg(feature = "api")]
pub mod analytics;
#[cfg(feature = "api")]
pub mod auth;
#[cfg(feature = "api")]
pub mod batch;
#[cfg(feature = "api")]
pub mod files;
pub mod health;
#[cfg(feature = "api")]
pub mod metrics;
#[cfg(feature = "api")]
pub mod modules;
pub mod papers;
#[cfg(feature = "api")]
pub mod papers_phase3;
pub mod repositories;
#[cfg(feature = "api")]
pub mod search;
#[cfg(feature = "api")]
pub mod settings;
#[cfg(feature = "api")]
pub mod streaming;
pub mod tasks;
#[cfg(feature = "api")]
pub mod tools;

#[cfg(feature = "api")]
pub use analytics::*;
#[cfg(feature = "api")]
pub use auth::*;
#[cfg(feature = "api")]
pub use batch::*;
#[cfg(feature = "api")]
pub use files::*;
pub use health::health_check;
#[cfg(feature = "api")]
pub use metrics::*;
#[cfg(feature = "api")]
pub use modules::*;
pub use papers::*;
#[cfg(feature = "api")]
pub use papers_phase3::*;
pub use repositories::*;
#[cfg(feature = "api")]
pub use search::*;
#[cfg(feature = "api")]
pub use settings::*;
#[cfg(feature = "api")]
pub use streaming::*;
pub use tasks::*;
#[cfg(feature = "api")]
pub use tools::*;
